export enum CollectionSortType {
  TITLE_ASC = 'TITLE_ASC',
  TITLE_DESC = 'TITLE_DESC',
  YEAR_ASC = 'YEAR_ASC',
  YEAR_DESC = 'YEAR_DESC',
}

export enum CollectionFilterType {
  ALL = 'ALL',
  IN_COLLECTION_ALL = 'IN_COLLECTION_ALL',
  IN_COLLECTION_OWNED = 'IN_COLLECTION_OWNED',
  IN_COLLECTION_WISHED = 'IN_COLLECTION_WISHED',
  NOT_IN_COLLECTION = 'NOT_IN_COLLECTION',
}
